---
runtime: php55
api_version: 1
threadsafe: true
default_expiration: 300s
handlers:
- url: "/services/2014/09/21/services-1/"
  static_files: services/2014/09/21/services-1/index.html
  upload: services/2014/09/21/services-1/index.html
- url: "/services/2014/09/22/services-2/"
  static_files: services/2014/09/22/services-2/index.html
  upload: services/2014/09/22/services-2/index.html
- url: "/services/2014/09/23/services-3/"
  static_files: services/2014/09/23/services-3/index.html
  upload: services/2014/09/23/services-3/index.html
- url: "/"
  static_files: index.html
  upload: index.html
- url: "/LICENSE"
  static_files: LICENSE
  upload: LICENSE
- url: "/README.md"
  static_files: README.md
  upload: README.md
- url: "/css/bootstrap.css"
  static_files: css/bootstrap.css
  upload: css/bootstrap.css
- url: "/css/bootstrap.min.css"
  static_files: css/bootstrap.min.css
  upload: css/bootstrap.min.css
- url: "/css/landing-page.css"
  static_files: css/landing-page.css
  upload: css/landing-page.css
- url: "/font-awesome-4.1.0/css/font-awesome.css"
  static_files: font-awesome-4.1.0/css/font-awesome.css
  upload: font-awesome-4.1.0/css/font-awesome.css
- url: "/font-awesome-4.1.0/css/font-awesome.min.css"
  static_files: font-awesome-4.1.0/css/font-awesome.min.css
  upload: font-awesome-4.1.0/css/font-awesome.min.css
- url: "/font-awesome-4.1.0/fonts/FontAwesome.otf"
  static_files: font-awesome-4.1.0/fonts/FontAwesome.otf
  upload: font-awesome-4.1.0/fonts/FontAwesome.otf
- url: "/font-awesome-4.1.0/fonts/fontawesome-webfont.eot"
  static_files: font-awesome-4.1.0/fonts/fontawesome-webfont.eot
  upload: font-awesome-4.1.0/fonts/fontawesome-webfont.eot
- url: "/font-awesome-4.1.0/fonts/fontawesome-webfont.svg"
  static_files: font-awesome-4.1.0/fonts/fontawesome-webfont.svg
  upload: font-awesome-4.1.0/fonts/fontawesome-webfont.svg
- url: "/font-awesome-4.1.0/fonts/fontawesome-webfont.ttf"
  static_files: font-awesome-4.1.0/fonts/fontawesome-webfont.ttf
  upload: font-awesome-4.1.0/fonts/fontawesome-webfont.ttf
- url: "/font-awesome-4.1.0/fonts/fontawesome-webfont.woff"
  static_files: font-awesome-4.1.0/fonts/fontawesome-webfont.woff
  upload: font-awesome-4.1.0/fonts/fontawesome-webfont.woff
- url: "/font-awesome-4.1.0/less/bordered-pulled.less"
  static_files: font-awesome-4.1.0/less/bordered-pulled.less
  upload: font-awesome-4.1.0/less/bordered-pulled.less
- url: "/font-awesome-4.1.0/less/core.less"
  static_files: font-awesome-4.1.0/less/core.less
  upload: font-awesome-4.1.0/less/core.less
- url: "/font-awesome-4.1.0/less/fixed-width.less"
  static_files: font-awesome-4.1.0/less/fixed-width.less
  upload: font-awesome-4.1.0/less/fixed-width.less
- url: "/font-awesome-4.1.0/less/font-awesome.less"
  static_files: font-awesome-4.1.0/less/font-awesome.less
  upload: font-awesome-4.1.0/less/font-awesome.less
- url: "/font-awesome-4.1.0/less/icons.less"
  static_files: font-awesome-4.1.0/less/icons.less
  upload: font-awesome-4.1.0/less/icons.less
- url: "/font-awesome-4.1.0/less/larger.less"
  static_files: font-awesome-4.1.0/less/larger.less
  upload: font-awesome-4.1.0/less/larger.less
- url: "/font-awesome-4.1.0/less/list.less"
  static_files: font-awesome-4.1.0/less/list.less
  upload: font-awesome-4.1.0/less/list.less
- url: "/font-awesome-4.1.0/less/mixins.less"
  static_files: font-awesome-4.1.0/less/mixins.less
  upload: font-awesome-4.1.0/less/mixins.less
- url: "/font-awesome-4.1.0/less/path.less"
  static_files: font-awesome-4.1.0/less/path.less
  upload: font-awesome-4.1.0/less/path.less
- url: "/font-awesome-4.1.0/less/rotated-flipped.less"
  static_files: font-awesome-4.1.0/less/rotated-flipped.less
  upload: font-awesome-4.1.0/less/rotated-flipped.less
- url: "/font-awesome-4.1.0/less/spinning.less"
  static_files: font-awesome-4.1.0/less/spinning.less
  upload: font-awesome-4.1.0/less/spinning.less
- url: "/font-awesome-4.1.0/less/stacked.less"
  static_files: font-awesome-4.1.0/less/stacked.less
  upload: font-awesome-4.1.0/less/stacked.less
- url: "/font-awesome-4.1.0/less/variables.less"
  static_files: font-awesome-4.1.0/less/variables.less
  upload: font-awesome-4.1.0/less/variables.less
- url: "/font-awesome-4.1.0/scss/font-awesome.scss"
  static_files: font-awesome-4.1.0/scss/font-awesome.scss
  upload: font-awesome-4.1.0/scss/font-awesome.scss
- url: "/fonts/glyphicons-halflings-regular.eot"
  static_files: fonts/glyphicons-halflings-regular.eot
  upload: fonts/glyphicons-halflings-regular.eot
- url: "/fonts/glyphicons-halflings-regular.svg"
  static_files: fonts/glyphicons-halflings-regular.svg
  upload: fonts/glyphicons-halflings-regular.svg
- url: "/fonts/glyphicons-halflings-regular.ttf"
  static_files: fonts/glyphicons-halflings-regular.ttf
  upload: fonts/glyphicons-halflings-regular.ttf
- url: "/fonts/glyphicons-halflings-regular.woff"
  static_files: fonts/glyphicons-halflings-regular.woff
  upload: fonts/glyphicons-halflings-regular.woff
- url: "/img/banner-bg.jpg"
  static_files: img/banner-bg.jpg
  upload: img/banner-bg.jpg
- url: "/img/intro-bg.jpg"
  static_files: img/intro-bg.jpg
  upload: img/intro-bg.jpg
- url: "/img/screenshot.png"
  static_files: img/screenshot.png
  upload: img/screenshot.png
- url: "/img/services/chicken.jpg"
  static_files: img/services/chicken.jpg
  upload: img/services/chicken.jpg
- url: "/img/services/duck.jpg"
  static_files: img/services/duck.jpg
  upload: img/services/duck.jpg
- url: "/img/services/egg.jpg"
  static_files: img/services/egg.jpg
  upload: img/services/egg.jpg
- url: "/js/bootstrap.js"
  static_files: js/bootstrap.js
  upload: js/bootstrap.js
- url: "/js/bootstrap.min.js"
  static_files: js/bootstrap.min.js
  upload: js/bootstrap.min.js
- url: "/js/jquery-1.11.0.js"
  static_files: js/jquery-1.11.0.js
  upload: js/jquery-1.11.0.js
- url: "/js/jquery.easing.min.js"
  static_files: js/jquery.easing.min.js
  upload: js/jquery.easing.min.js
- url: "/js/landing-page.js"
  static_files: js/landing-page.js
  upload: js/landing-page.js
